version: '3.8'

services:
  web:
    build: .
    container_name: rsfw_interactive_staging
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - APP_ENV=staging
    restart: unless-stopped